# Generated by Django 6.0.2 on 2026-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='approvals_required',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='absence',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_absences', to='api.employee'),
        ),
        migrations.AddField(
            model_name='position',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='requires_dual_approval',
            field=models.BooleanField(default=False),
        ),
    ]
