# Generated by Django 6.0.3 on 2026-03-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('vacation', 'Urlaub'), ('sick', 'Krank'), ('homeoffice', 'Homeoffice'), ('meeting', 'Besprechung'), ('other', 'Sonstiges')], max_length=20),
        ),
        migrations.CreateModel(
            name='TimeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='api.timeentry')),
            ],
            options={
                'verbose_name': 'Pause',
                'verbose_name_plural': 'Pausen',
            },
        ),
    ]
