# Generated by Django 6.0.3 on 2026-03-08 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_absence_absence_type_timebreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='edit_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_manual_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimeCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_time', models.DateTimeField()),
                ('new_end_time', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('denied', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_corrections', to='api.employee')),
                ('time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='api.timeentry')),
            ],
            options={
                'verbose_name': 'Korrekturantrag',
                'verbose_name_plural': 'Korrekturanträge',
                'ordering': ['-created_at'],
            },
        ),
    ]
