# Generated by Django 6.0.3 on 2026-03-08 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_timeentry_edit_reason_timeentry_is_manual_edit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebreak',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
