# Generated by Django 6.0.3 on 2026-03-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fix_time_fields_allow_manual_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('diverse', 'Divers')], default='male', max_length=10),
        ),
    ]
